name: Publish stories if changed

on:
  push:
    branches:
      - main
    paths:
      - stories/**
      - src/components/**
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: "☁️ checkout repository"
        uses: actions/checkout@v4

      - name: "🔧 setup node"
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: "🔧 install npm@latest"
        run: npm i -g npm@latest

      - name: "📦 install dependencies"
        run: npm install

      - name: "📦 build Storybook"
        run: npx build-storybook

      - name: "🚀 deploy static"
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_branch: storybook-static
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
          commit_message: ${{ github.event.head_commit.message }}
          enable_jekyll: false